### ISSUE TITLE
AVCaptureSession/AVCaptureDevice not available in Catalyst 13.0, Xcode 12.5 beta 3

### ISSUE THREAD

**Issue by rocketnik** [stripe/stripe-ios#1786]
## Summary
I get compilation errors in
STPCameraView.swift and STPCardScanner.swift:
'AVCaptureSession' is only available in Mac Catalyst 14.0 or newer
'AVCaptureDevice' is only available in Mac Catalyst 14.0 or newer

## Code to reproduce
Compile on Xcode 12.5 beta 3
Compile a project including the Stripe SDK.
Project deployment Target: iOS 13 (Catalyst)
Project compiled for Catalyst Mac
Doing so on an M1 Mac (I can't check on Intel at the moment)

## iOS version
Mac Catalyst 13.0

## Installation method
The SDK was added via CocoaPods 1.10.1

## SDK version
Version: 21.3.1

## Other information
I had version 21.1.0 of the Stripe SDK before. It worked fine so far.
Here is what I changed:
Intel -> M1
Xcode 12.4 -> Xcode 12.5 beta 3
SDK 21.1.0 -> 21.3.1

What does work:
M1, SDK 21.3.1, Xcode 12.4

What does not work
M1, SDK 21.3.1, Xcode 12.5 beta 3

**Comment by rocketnik** [comment]
![Uploading Screen Shot 2021-04-02 at 12.52.28.png…]()

**Comment by rocketnik** [comment]
<img width="812" alt="Screen Shot 2021-04-02 at 12 52 28" src="https://user-images.githubusercontent.com/8329809/113409884-79b07000-93b2-11eb-96df-fe7d5b247d40.png">

**Comment by csabol-stripe** [comment]
Thanks for the report @rocketnik, we'll get the latest beta set up and find a fix for this

**Comment by davidme-stripe** [comment]
This should be fixed in [21.4.0](https://github.com/stripe/stripe-ios/releases/tag/21.4.0).
