### ISSUE TITLE
Method 'isEqual(to:)' with Objective-C selector 'isEqualTo:' conflicts with method 'isEqual(to:)' from superclass 'NSObject'

### ISSUE THREAD

**Issue by Boobesh** [stripe/stripe-ios#1822]
## Summary

I get a compilation error while building my project that integrated with Stripe SDK via SPM. Getting this error on STPToken.swift file and STPToken class in this function. L.No. 73

 `@objc func isEqual(to object: STPToken?) -> Bool ` 

Method 'isEqual(to:)' with Objective-C selector 'isEqualTo:' conflicts with method 'isEqual(to:)' from superclass 'NSObject' with the same Objective-C selector

![image](https://user-images.githubusercontent.com/31337369/122203767-00f28780-cebc-11eb-9ab2-17a78dd7dd7e.png)

## Code to reproduce

Stripe SDK integrated into a Mac Catalyst Project via SPM on Xcode 13 and macOS 12.

I have tried to build on both iOS and macOS still got the same error. 

It works fine in Xcode 12.5

## iOS version

macOS 12.0 Beta 1 (21A5248p) 
iOS 15 Beta 1

## Installation method

SPM

## SDK version

21.5.0
21.5.1
21.6.0

First I got this error in 21.5.0 So I moved to the next version (21.5.1) and tried but not worked so moved to the very latest version 21.6.0 in the latest version also issue persists.

## Other information

It works fine in Xcode 12.5

**Comment by davidme-stripe** [comment]
Thanks for filing this! We'll fix this and other Xcode 13 errors and warnings in the next update. If you need a workaround for now, you can delete `@objc` from the referenced `@objc func isEqual` line.

**Comment by Boobesh** [comment]
@davidme-stripe We're using it as an SPM so can't edit the file.. It will be nice if you guys plan and release the next update as soon as possible.

**Comment by davidme-stripe** [comment]
We fixed this in [version 21.7.0](https://github.com/stripe/stripe-ios/releases/tag/21.7.0).
